/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Message = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const Rule = IDL.Record({ 'response' : IDL.Text, 'keyword' : IDL.Text });
export const Template = IDL.Record({ 'content' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'createRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createTemplate' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteRule' : IDL.Func([IDL.Int], [], []),
  'deleteTemplate' : IDL.Func([IDL.Int], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllRules' : IDL.Func([], [IDL.Vec(Rule)], ['query']),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setFallback' : IDL.Func([IDL.Text], [], []),
  'toggleBot' : IDL.Func([IDL.Bool], [], []),
  'updateRule' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
  'updateTemplate' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Message = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const Rule = IDL.Record({ 'response' : IDL.Text, 'keyword' : IDL.Text });
  const Template = IDL.Record({ 'content' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    'createRule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createTemplate' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteRule' : IDL.Func([IDL.Int], [], []),
    'deleteTemplate' : IDL.Func([IDL.Int], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllRules' : IDL.Func([], [IDL.Vec(Rule)], ['query']),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setFallback' : IDL.Func([IDL.Text], [], []),
    'toggleBot' : IDL.Func([IDL.Bool], [], []),
    'updateRule' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
    'updateTemplate' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };